### ISSUE TITLE
Support text-decoration style parameter

### ISSUE THREAD

**Issue by kmorel** [sandialabs/toyplot#193]
When rendering text with a web link (i.e. `<a href="link">text</a>`) the text is rendered with a fairly unpleasant line underneath it. I would like to get rid of that line by setting the `text-decoration: none` style parameter. However, toyplot refuses to apply this style.

**Comment by tshead2** [comment]
It turns-out that SVG hyperlinks are styled differently depending on context - if you're looking at a standalone SVG document, the hyperlinks have no special styling.  If you're looking at SVG embedded in a web page (e.g. Jupyter notebook) then the hyperlinks inherit their appearance from document / browser defaults.

Since The Toyplot Way is to be consistent, I've imposed an explicit default style for Toyplot hyperlinks in master (steel blue color, no underline), and enabled support for the CSS `text-decoration-line` property in case anyone wants a more traditional appearance.

**Comment by kmorel** [comment]
The steel blue color seems to overwrite any color property set in the text. Is there a way to change the color of the text in a link?

**Comment by tshead2** [comment]
You can style the hyperlink directly, with some careful quoting:

    "<a href='/path/to/content' style='fill: white'>Click Me!</a>"

See https://toyplot.readthedocs.io/en/latest/text.html#rich-text for details.

**Comment by kmorel** [comment]
Got it. (I guess I could of looked that up, but it is easier to bug Tim.)
