### ISSUE TITLE
Color conversion code to css contains an error

### ISSUE THREAD

**Issue by elissasoroj** [sandialabs/toyplot#210]
Hello!

I am trying to make custom markers using the following code:
`toyplot.marker.create(shape="s", mstyle={"fill":toyplot.color.rgb(104, 94, 164), "opacity":0.9})`

This alone works fine, but when I try to display it in a legend, I get the following error:
```
canvas.legend([
    ("s=0", marker_a),
    ("s=0.001", marker_b),
    ("s=0.01", marker_c),
    ("s=0.1", marker_d),
    ],
    corner=("top-right", 100, 100, 125),
    );
```

<img width="978" alt="Screen Shot 2022-11-01 at 9 00 05 AM" src="https://user-images.githubusercontent.com/71294603/199238405-30eef260-14bd-4fc4-842f-1c215b557f6f.png">

I tried inputting the color as rgb (as above) and also as `toyplot.color.Palette()[0]` and `toyplot.color.css("#68c2a4")`, to try to get it to bypass the conversion, but it always throws the same error. 

I love this plotting library! Thank you for maintaining it :)

~Elissa

**Comment by tshead2** [comment]
@elissasoroj - many thanks for the kind words and the feedback!  The problem here is that Toyplot only allows valid CSS *strings* as the values in style dictionaries (I just realized that the documentation doesn't make this clear, and the error message isn't usable, so that's on me) ... in your case you could use any of the following:

`
marker = toyplot.marker.create(shape="s", mstyle={"fill":"rgb(104, 94, 164)", "opacity":"0.9"})
marker = toyplot.marker.create(shape="s", mstyle={"fill":"#68c2a4", "opacity":"0.9"})
marker = toyplot.marker.create(shape="s", mstyle={"fill":"steelblue", "opacity":"0.9"})
`

`toyplot.color.css()` and similar methods are about converting *from* CSS to Toyplot's internal color representation, which is a Numpy array.  Apologies for the confusion.

Cheers,
Tim
