### ISSUE TITLE
Download CSV missing extension

### ISSUE THREAD

**Issue by ma-schmidt** [sandialabs/toyplot#51]
This is a very minimal upgrade to do. I was just reading the "getting started" page and when I tried the "download CSV" feature of a plot by right clicking on the curve, it would download simply as "download" without extension. The document is still a csv, but it would be more user-friendly if the file was already marked as .csv.

**Comment by tshead2** [comment]
@ma-schmidt : This seems highly browser / configuration-dependent, which browser are you using?  

* When I download CSV in Safari on OS X, it opens a new tab with the file contents.  When I choose File > Save As, the file dialog opens with "Untitled.csv" as the default filename.
* When I download CSV with Firefox on OS X, it offers to open the file in Excel or save it ... if I save it, it ends-up in my Downloads directory with a <random>.csv filename.
* When I download CSV with Chrome on OS X, it shows-up in my Downloads directory as "download.cv" and is opened in Excel.

**Comment by ma-schmidt** [comment]
Uhmmmm, yeah, it seems very dependent on the configuration. I am using Windows 8.1. The behavior I was describing was with chrome. I tried it with firefox and there is still no extension.

**Comment by tshead2** [comment]
@ma-schmidt : I've just pushed a change to specify a default filename (currently "toyplot.csv") for browsers that support it.  That should include current versions of Firefox, Chrome, Opera, and Android.  IE, Safari, and iOS Safari will continue to open the file in a separate tab without any default filename.

http://caniuse.com/#search=download for details on browser support.

Fixed in b8c6ca1e65a60a8c78dab09b881a6e76becf7cac
