### ISSUE TITLE
There seems to be a bug in the Matrix Visualization part of the doc [TypeError: matrix() got an unexpected keyword argument 'title']

### ISSUE THREAD

**Issue by knightofni** [sandialabs/toyplot#60]
See attached screenshot

**TypeError: matrix() got an unexpected keyword argument 'title'**

<img width="798" alt="screen shot 2015-07-13 at 7 53 56 pm" src="https://cloud.githubusercontent.com/assets/3415960/8649054/fcc60b2e-2998-11e5-9485-76f64ec3da23.png">

**Comment by tshead2** [comment]
@knightofni - ack!  Thanks for calling my attention to this.  I haven't yet figured-out a way to catch these errors when converting notebooks to documentation.  Fixed in bcbcfd3f1c1f45f981663e22071dfa0133829885.

One other thing to be aware of: this documentation is for git master, not the current PyPI release, which is 0.5.0.  It normally isn't an issue unless there's an API change, as there was in this case.

Cheers,
Tim

**Comment by knightofni** [comment]
@tshead2 thanks. The matrixes look really nice ! Just installed 0.6 from source.
